# Generated by Django 5.2 on 2026-10-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "sos_college",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "sos_course",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=50)),
                ("course_id", models.IntegerField()),
                ("course_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "sos_subject",
            },
        ),
    ]
